[profile.default]
src = "src"
out = "out"
libs = ["lib"]
gas_reports = ["*"]

ffi = false

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether or not to use the Yul intermediate representation compilation pipeline
via_ir = true
evm_version = "cancun"

[fuzz]
fail_on_revert = true
runs = 1000
corpus = "corpus" 
# The number of threads to use for fuzzing
threads = 4

[invariant] #invariant section
fail_on_revert = true
runs = 1300
depth = 23


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
